version: "3.7"

networks:
  internal:
    driver: bridge

services:
  
  client:
    build:
      context: ./client
      args:
        - VUE_APP_STREAM_PROXY_URL=http://172.20.20.31:3000
        - VUE_APP_STREAM_URL=http://172.20.20.31:8000/black.mp3
    links:
      - proxy
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
     - proxy

  proxy:
    build: ./proxy
    ports: 
        - "3000:3000"
    expose: 
        - "3000"
    networks:
      - internal
    depends_on:
      - icecast

  icecast:
    build: ./icecast
    ports: 
        - "8000:8000"
    expose: 
        - "8000"
    networks:
      - internal
    depends_on:
      - liquidsoap

  liquidsoap:
    build: ./liquidsoap
    volumes:
      - /home/vagrant/radio-g/music:/opt/liquidsoap/playlists/mp3
      - ./infra/logs/liquidsoap:/var/log/liquidsoap/
    networks:
      - internal